Force using manage.py when executing celerytestworker.
Our project uses django_nose, so this line lead to the following
exception before this commit:

    Exception: Celery worker failed: nosetests celerytestworker --verbosity=1